### ISSUE TITLE
source host "any" in conjonction with tcp6 protocol ever mismatched

### ISSUE THREAD

**Issue by peekjef72** [peekjef72/cnxwatch_exporter#6]
With configuration

```yml
sockets:
  - name: hostname-grafana 
    srcHost: "*"
    port: '3000'
    status: listen
    protocol: tcp6

```
the results from a scrap are :

```text
# HELP connection_status_count number of socket with same parameter.
# TYPE connection_status_count gauge
connection_status_count{dsthost="*",dstport="*",name="hostname-grafana",process="",protocol="tcp6",srchost="*",srcport="3000",status="listen"} 0

# HELP connection_status_up Connection status of the socket (0 down - 1 up).
# TYPE connection_status_up gauge
connection_status_up{dsthost="*",dstport="*",name="hostname-grafana",process="",protocol="tcp6",srchost="*",srcport="3000",status="listen"} 0
```

in the same time the netstat cmd returns:
```bash

# netstat -nap | grep :3000
tcp6       0      0 :::3000                 :::*                    LISTEN      1401/grafana-server 

```
